"""add_severity_and_sheet_row_hash_to_events

Revision ID: e34f9c9bf6e5
Revises: 
Create Date: 2026-03-08 13:16:56.834881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34f9c9bf6e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('severity', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('sheet_row_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_events_sheet_row_hash'), 'events', ['sheet_row_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_sheet_row_hash'), table_name='events')
    op.drop_column('events', 'sheet_row_hash')
    op.drop_column('events', 'severity')
    # ### end Alembic commands ###
